// Mocks generated by Mockito 5.4.5 from annotations
// in snap_jp_learn_app/test/services/sync_engine_resync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hive_flutter/hive_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:snap_jp_learn_app/core/ui_state.dart' as _i9;
import 'package:snap_jp_learn_app/models/offline_task.dart' as _i8;
import 'package:snap_jp_learn_app/models/post.dart' as _i4;
import 'package:snap_jp_learn_app/services/offline_queue_service.dart' as _i7;
import 'package:snap_jp_learn_app/services/sync_api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SyncApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncApiService extends _i1.Mock implements _i2.SyncApiService {
  MockSyncApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> pingServer() => (super.noSuchMethod(
        Invocation.method(
          #pingServer,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Post>> pullPosts() => (super.noSuchMethod(
        Invocation.method(
          #pullPosts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
      ) as _i3.Future<List<_i4.Post>>);

  @override
  _i3.Future<void> pushPosts(List<_i4.Post>? posts) => (super.noSuchMethod(
        Invocation.method(
          #pushPosts,
          [posts],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i5.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i3.Stream<_i5.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i3.Stream<_i5.BoxEvent>.empty(),
      ) as _i3.Stream<_i5.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i3.Future<Iterable<int>>.value(<int>[]),
      ) as _i3.Future<Iterable<int>>);

  @override
  _i3.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [OfflineQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineQueueService extends _i1.Mock
    implements _i7.OfflineQueueService {
  MockOfflineQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.OfflineQueueStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i7.OfflineQueueStatus.idle,
      ) as _i7.OfflineQueueStatus);

  @override
  int get taskCount => (super.noSuchMethod(
        Invocation.getter(#taskCount),
        returnValue: 0,
      ) as int);

  @override
  List<_i8.OfflineTask> get tasks => (super.noSuchMethod(
        Invocation.getter(#tasks),
        returnValue: <_i8.OfflineTask>[],
      ) as List<_i8.OfflineTask>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i9.UiState<String>> addTask({
    required String? type,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [],
          {
            #type: type,
            #payload: payload,
          },
        ),
        returnValue: _i3.Future<_i9.UiState<String>>.value(
            _i6.dummyValue<_i9.UiState<String>>(
          this,
          Invocation.method(
            #addTask,
            [],
            {
              #type: type,
              #payload: payload,
            },
          ),
        )),
      ) as _i3.Future<_i9.UiState<String>>);

  @override
  _i3.Future<_i9.UiState<String>> addPostTask(_i4.Post? post) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPostTask,
          [post],
        ),
        returnValue: _i3.Future<_i9.UiState<String>>.value(
            _i6.dummyValue<_i9.UiState<String>>(
          this,
          Invocation.method(
            #addPostTask,
            [post],
          ),
        )),
      ) as _i3.Future<_i9.UiState<String>>);

  @override
  _i3.Future<_i9.UiState<String>> addReactionTask({
    required String? postId,
    required String? reactionType,
    required bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReactionTask,
          [],
          {
            #postId: postId,
            #reactionType: reactionType,
            #isActive: isActive,
          },
        ),
        returnValue: _i3.Future<_i9.UiState<String>>.value(
            _i6.dummyValue<_i9.UiState<String>>(
          this,
          Invocation.method(
            #addReactionTask,
            [],
            {
              #postId: postId,
              #reactionType: reactionType,
              #isActive: isActive,
            },
          ),
        )),
      ) as _i3.Future<_i9.UiState<String>>);

  @override
  _i3.Future<_i9.UiState<String>> addLearningHistoryTask({
    required String? cardId,
    required String? result,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLearningHistoryTask,
          [],
          {
            #cardId: cardId,
            #result: result,
          },
        ),
        returnValue: _i3.Future<_i9.UiState<String>>.value(
            _i6.dummyValue<_i9.UiState<String>>(
          this,
          Invocation.method(
            #addLearningHistoryTask,
            [],
            {
              #cardId: cardId,
              #result: result,
            },
          ),
        )),
      ) as _i3.Future<_i9.UiState<String>>);

  @override
  _i3.Future<_i9.UiState<int>> processQueue() => (super.noSuchMethod(
        Invocation.method(
          #processQueue,
          [],
        ),
        returnValue:
            _i3.Future<_i9.UiState<int>>.value(_i6.dummyValue<_i9.UiState<int>>(
          this,
          Invocation.method(
            #processQueue,
            [],
          ),
        )),
      ) as _i3.Future<_i9.UiState<int>>);

  @override
  _i3.Future<void> clearQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
